### ISSUE TITLE
Broken URL must be shown

### ISSUE THREAD

**Issue by niteeshbhat** [niteeshbhat/HbbTV_DVB_Conformance_Frontend#70]
http://10.4.252.64/HbbTV/org.hbbtv_MDEVSYNC018/MDEVSYNC018-1.mpd

As live segments are not found, at least broken url list should be visible.

**Comment by eceozturk** [comment]
The encountered issue is not about the BrokenURLs but rather about the following:
- Sometimes the segment boxes file is empty or not compatible with XML syntax because of unknown characters. To avoid crashing of the software, the existence and the compatibility of these files need to be checked before further processing.

This issue is fixed by PR #79
